parameters:
  - name: language
    type: string
    values:
      - dotnet
      - python
      - nodejs
  - name: workingDirectory
    type: string
  - name: repositoryName
    type: string

stages:
  - stage: parameters
    displayName: Parameters
    jobs:
      - job: show_parameters
        displayName: 'Show Parameters'
        steps:
          - script: |
              echo "language --> ${{ parameters.language }}" 
              echo "workingDirectory --> ${{ parameters.workingDirectory }}" 
              echo "repositoryName --> ${{ parameters.repositoryName }}" 

  - ${{ if eq(parameters.language, 'dotnet') }}: 
    - template: dotnet-build-stage.yml
      parameters:
        workingDirectory: ${{ parameters.workingDirectory }}
  
  - template: contenerization-stage.yml
    parameters:
      containerRegistry: 'DockerHub'
      repository: ${{ parameters.repositoryName }}
      buildContext: ${{ parameters.workingDirectory }}
  
  - template: deployment-stage.yml