parameters:
  - name: language
    type: string
    values:
      - dotnet
      - python
      - nodejs
  - name: workingDirectory
    type: string
  - name: repositoryName
    type: string

variables:
  - template: vars.yml
    parameters:
      language: ${{ parameters.language }}      

stages:
  - ${{ if eq(parameters.language, 'dotnet') }}: 
    - template: dotnet-build-stage.yml
      parameters:
        workingDirectory: ${{ parameters.workingDirectory }}
  
  - template: contenerization-stage.yml
    parameters:
      containerRegistry: '${{ variables.containerRegistry }}'
      repository: '${{ variables.dockerHubUsername }}/${{ parameters.repositoryName }}'
      buildContext: ${{ parameters.workingDirectory }}
  
  - template: deployment-stage.yml
    parameters:
      azureSubscription: '${{ variables.azureSubscription }}'
      containerAppName: '${{ variables.containerAppName }}'
      resourceGroup: '${{ variables.resourceGroupName }}'
      imageToDeploy: '${{ variables.containerRegistryServer }}/${{ variables.dockerHubUsername }}/${{ parameters.repositoryName }}:$(Build.BuildId)'
