parameters:
  - name: repository
    type: string

stages:
  - stage: deployment
    displayName: 'Deployment'
    
    jobs:
      
      - job: deploying
        displayName: 'Deploying'
        
        steps:
          
          - task: AzureContainerApps@1
            name: deploy_containerapp
            displayName: 'Deploy ContainerApp'
            inputs:
              azureSubscription: '${{ variables.azureSubscription }}'
              containerAppName: '${{ variables.containerAppName }}'
              resourceGroup: '${{ variables.resourceGroupName }}'
              imageToDeploy: '${{ variables.containerRegistryServer }}/${{ parameters.repository }}:$(Build.BuildId)'