parameters:
  - name: azureSubscription
    type: string
  - name: containerAppName
    type: string
  - name: resourceGroup
    type: string
  - name: imageToDeploy
    type: string

stages:
  - stage: deployment
    displayName: 'Deployment'
    
    jobs:
      
      - job: deploying
        displayName: 'Deploying'
        
        steps:

          - task: AzureContainerApps@1
            name: deploy_containerapp
            displayName: 'Deploy ContainerApp'
            inputs:
              azureSubscription: '${{ parameters.azureSubscription }}'
              containerAppName: '${{ parameters.containerAppName }}'
              resourceGroup: '${{ parameters.resourceGroup }}'
              imageToDeploy: '${{ parameters.imageToDeploy }}'